version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: check for maven
          command: which mvn

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test