version: 2
jobs:
  build-and-test:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - checkout
      # - awk out the config info in ./jenkins_home/jobs/*/config.xml
      # - spin up jenkins server with jenkins_home

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test