version: 2
jobs:
  build-and-test:
    steps:
      - checkout
      - run:
          name: check for maven
          command: which maven

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test