version: 2
mvn_cache_key: &mvn_cache_key mvn-dependency-cache-{{ checksum "pom.xml" }}
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: *mvn_cache_key
      - run:
          name: Fetch dependencies
          command: mvn dependency:go-offline
      - save_cache:
          key: *mvn_cache_key
          paths:
            - ~/.m2
      - run:
          name: Build the ghost-inspector plugin
          command: mvn package
      - run:
          name: Save the plugin to our workspace
          command: |
            mkdir /tmp/plugin
            cp target/ghost-inspector.hpi /tmp/plugin/
      - persist_to_workspace:
          root: /tmp/plugin/
          paths: 
            - ghost-inspector.hpi

  test:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - attach_workspace:
          at: /tmp/plugin/
      - setup_remote_docker
      - checkout
      - run:
          name: Swap test secrets into Jenkins jobs
          command: |
            sed -i "s/{{APIKEY}}/$APIKEY/g" ./jenkins_home/jobs/*/config.xml
            sed -i "s/{{SUITEID}}/$SUITEID/g" ./jenkins_home/jobs/*/config.xml
      - run:
          name: Copy new ghost-inspector.hpi plugin to jenkins_home, named as .jpi (so it will install)
          command: cp /tmp/plugin/ghost-inspector.hpi ./jenkins_home/plugins/ghost-inspector.jpi
      - run:
          name: Build our Docker (Jenkins) image to run plugin tests
          command: docker build -t jenkins-test:0.1.$CIRCLE_BUILD_NUM .
      - run:
          name: Start Jenkins
          command: |
            docker network create temp-network
            docker run -d \
              -p 8080:8080 \
              --network temp-network \
              --name jenkins \
              jenkins-test:0.1.$CIRCLE_BUILD_NUM
      - run:
          name: Pause to let Jenkins fire up
          command: sleep 60
      - run:
          name: Test the plugin - standard job
          command: |
            docker exec \
              -e JOB=standard-test \
              jenkins /tmp/scripts/test-plugin.sh
      - run:
          name: Test the plugin - pipeline job
          command: |
            docker exec \
              -e JOB=pipeline-test \
              jenkins /tmp/scripts/test-plugin.sh
      - store_artifacts:
          path: /tmp/plugin/ghost-inspector.hpi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
